# Generated by Django 5.1.3 on 2024-11-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_contact_delete_testtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
