# Generated by Django 5.1.3 on 2024-11-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_alter_contact_phone_id_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
