# Generated by Django 5.1.3 on 2024-11-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_userinfo_secret_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="secret_key",
            field=models.CharField(
                blank=True,
                default="gAAAAABnN6L63YNu7D8WiT4zeh5zAvJG_s8KvJyXvvrTqNHI2le0u0KNubJtP46XxFjbItor4g7Svz7wIch4wcctx9b5SkGcgg==",
                max_length=255,
            ),
        ),
    ]
