# Generated by Django 5.1.3 on 2024-11-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_userinfo_secret_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="secret_key",
            field=models.CharField(
                blank=True,
                default="gAAAAABnN8Go2oul5m86dxsUvNmm4ac4x9nBqcmIOBvGRcpnHdhMv-Vo0qPLMKrnCez7O9WEdL114nHiSOf_iE_xOHidJ9eiRQ==",
                max_length=255,
            ),
        ),
    ]
