# Generated by Django 5.1.3 on 2024-11-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_userinfo_secret_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="has_yandex_2fa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="made_2fa",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="secret_key",
            field=models.CharField(
                default="gAAAAABnN-Bszp4BJYBEgzQhfbcQdZS-lyWv4S2jNmnRrN0jfy0fwJ2rONXUTBNu3eYCTIwtjGA2fpe4dq8zaqpLTkH-QBypVw==",
                max_length=255,
            ),
        ),
    ]
