# Generated by Django 5.1.3 on 2024-11-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_userinfo_has_yandex_2fa_userinfo_made_2fa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="secret_key",
            field=models.CharField(
                default="gAAAAABnPFetC_ZU66-zbGFjvEFgsRKC6JC8QoUmJ7B93wozIRCaxQuUhOXmpOoGt184qykRCvNa0BUtn_1Wy5gAUcAabQ7T-A==",
                max_length=255,
            ),
        ),
    ]
