# Generated by Django 5.1.3 on 2024-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_userinfo_secret_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="secret_key",
            field=models.CharField(
                default="gAAAAABnPFfUpqx0pIB9qXtxjjILxIWYtHBzWlYGfh7qzjUv4O5HnhRWr50Vy2FVfAYz_oyDKeT_Mvd5VpdVjVVQlydCRiLtww==",
                max_length=255,
            ),
        ),
    ]
