# Generated by Django 5.1.3 on 2024-11-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_userinfo_secret_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="secret_key",
            field=models.CharField(
                default="gAAAAABnPhRIaPnPoYxLIeiJO8qtz7TQA0CKpLWUl5ibGn3pKIAN9QsqGrHgg36O045jjzGEj5glvzR_UiDIKugZemy58tkaHA==",
                max_length=255,
            ),
        ),
    ]
