# Generated by Django 5.1.3 on 2024-11-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_userinfo_telegram_username_alter_userinfo_secret_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Telegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("chat_id", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="secret_key",
            field=models.CharField(
                default="gAAAAABnPjPpVuujnMkspbtxIZQvTrpPAkpz57nvHuriWZLOb1MgC0wIo5Tr_PPf6_YoVcGsJWpr4rU78oGLlRDPkp5sBGzNcg==",
                max_length=255,
            ),
        ),
    ]
