# Generated by Django 5.1.3 on 2024-11-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecretcode',
            name='connect_2auf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersecretcode',
            name='secret_code_alise',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersecretcode',
            name='secret_code_mobile',
            field=models.TextField(blank=True),
        ),
    ]
